### ISSUE TITLE
todo lists

### ISSUE THREAD

**Issue by snmsts** [snmsts/cl-language-server#1]
- [x] rename system.
- [x] crack slynk.lisp into some files.
- [ ] ci to test repl.
- [ ] apply one package for a file policy?
- [ ] understand slynk protocol/[langserver](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md).
- [ ] support json-rpc.
- [ ] rewrite memo.lisp to memo.md and in the same form as langserver do.
